version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd

  apisix:
    image: apache/apisix:3.2.0-debian
    volumes:
      - ./docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    volumes:
      - ./docker/dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    environment:
      - APISIX_DASHBOARD_USER=${ADMIN_USER}
      - APISIX_DASHBOARD_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      - KEYCLOAK_USER=${ADMIN_USER}
      - KEYCLOAK_PASSWORD=${ADMIN_PASSWORD}
      - DB_VENDOR=h2
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "8080:8080"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.2.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  etcd_data:
  grafana_data: