apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - prometheus
  - key-auth
  - basic-auth
  - jwt-auth
  - openid-connect